import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import SideBar from '../components/SideBar'
import MakePost from '../components/MakePost'
import HomeBar from '../components/HomeBar'
import PostsArea from '../components/PostsArea'
import Post from '../models/Post'
import connectMongo from '../utils/connectMongo'
import {AiFillHeart, 
  AiOutlineHeart, 
  AiOutlineRetweet,
  AiOutlineShareAlt} from 'react-icons/ai'

export default function Home({data}) {
  const postsArray = data
  
  return (
    <div className='column'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid}>
        <div className={styles.sidebarcolumn}>
          <SideBar></SideBar>
        </div>
        <div className={styles.postcolumn}>
        <div className={styles.stickitup}>
            <HomeBar />
            <MakePost></MakePost>
        </div>
          <div><PostsArea posts = {postsArray}></PostsArea></div>
        </div>
        
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  try {
    await connectMongo()
    const data = await Post.find({}).sort({date:-1}).populate('user').lean()
    const posts = await JSON.parse(JSON.stringify(data))
    return {
      props: {
        data:JSON.parse(JSON.stringify(data))        
      }
    }
  } catch (error) {
    return {
      props: {
        error: JSON.parse(JSON.stringify(error))
      }
    }
  }
}