import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import SideBar from '../components/SideBar'
import Post from '../components/Post'
export default function Home() {
  return (
    <div className='column'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid}>
        <div className={styles.sidebarcolumn}>
          <SideBar></SideBar>
        </div>
        <div className={styles.postcolumn}>
          <Post></Post>
        </div>
      </div>
    </div>
  )
}
